name: Build and Release Keycloak Theme

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test:run

      - name: Build Keycloak theme
        run: npm run build-keycloak-theme

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keycloak-theme-jars
          path: |
            dist_keycloak/*.jar
          retention-days: 90

      - name: Attach JARs to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_keycloak/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
